### ISSUE TITLE
Remove IDE-specific settings and update .gitignore

### ISSUE THREAD

**Issue by snicoll** [wavefrontHQ/springboot-autoconfigure#4]
It looks like IDE-settings (`.idea` + iml files) were pushed by accident. If that's the case, it would be nice to remove them and update `.gitignore` so that they don't get re-added.

**Comment by panghy** [comment]
Actually, IntelliJ likes to suggests adding their settings files these days... we can still remove them though

**Comment by snicoll** [comment]
I haven't really found a good way to share settings while still keeping the ability to refresh the project when new dependencies are added. When I cloned this repo and opened it in my IDE, it started to modify some files and that doesn't sound right to me.

Also, there are [two iml files](https://github.com/wavefrontHQ/springboot-autoconfigure/tree/61995c94befa3d75b3e1207ee5c3294b774f795d) for the same module at the moment.
